[project]
name = "fast-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.116.1",
    "htmx>=0.0.0",
    "jinja2>=3.1.6",
    "sqlmodel>=0.0.24",
    "uvicorn>=0.35.0",
]
